name: sync-github-repos

on:
  schedule:
    - cron: '15 0 * * 1'
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  sync-repos-to-emu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      # source
      - name: get source app token
        uses: actions/create-github-app-token@v2
        id: source-app-token
        with:
          app-id: ${{ vars.SOURCE_APP_ID }}
          private-key: ${{ secrets.SOURCE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      # target
      - name: get target app token
        uses: actions/create-github-app-token@v2
        id: target-app-token
        with:
          app-id: ${{ vars.EMU_APP_ID }}
          private-key: ${{ secrets.EMU_APP_PRIVATE_KEY }}
          owner: joshjohanning-emu
      - name: Bulk GitHub Repository Sync
        uses: joshjohanning/bulk-github-repo-sync-action@v1
        with:
          repo-list-file: repos-emu.yml
          source-github-token: ${{ steps.source-app-token.outputs.token }}
          target-github-token: ${{ steps.target-app-token.outputs.token }}
          overwrite-repo-visibility: true # overwrite repo visibility with what is in yml file; defaults to false
          force-push: true

  sync-repos-to-ghe:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      # source
      - name: get source app token
        uses: actions/create-github-app-token@v2
        id: source-app-token
        with:
          app-id: ${{ vars.SOURCE_APP_ID }}
          private-key: ${{ secrets.SOURCE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      # target
      - name: get target app token
        uses: actions/create-github-app-token@v2
        id: target-app-token
        with:
          app-id: ${{ vars.GHE_APP_ID }}
          private-key: ${{ secrets.GHE_APP_PRIVATE_KEY }}
          owner: joshjohanning-org
          github-api-url: https://api.customersuccess.ghe.com
      - name: Bulk GitHub Repository Sync
        uses: joshjohanning/bulk-github-repo-sync-action@v1
        with:
          repo-list-file: repos-ghe.yml
          source-github-token: ${{ steps.source-app-token.outputs.token }}
          target-github-token: ${{ steps.target-app-token.outputs.token }}
          overwrite-repo-visibility: true # overwrite repo visibility with what is in yml file; defaults to false
          force-push: true
          target-github-api-url: https://api.customersuccess.ghe.com

  sync-repos-to-ghec:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      # target
      - name: get target app token
        uses: actions/create-github-app-token@v2
        id: target-app-token
        with:
          app-id: ${{ vars.GHEC_APP_ID }}
          private-key: ${{ secrets.GHEC_APP_PRIVATE_KEY }}
          owner: joshjohanning-org
      - name: Bulk GitHub Repository Sync
        uses: joshjohanning/bulk-github-repo-sync-action@v1
        with:
          repo-list-file: repos-ghec.yml
          source-github-token: ${{ steps.target-app-token.outputs.token }}
          target-github-token: ${{ steps.target-app-token.outputs.token }}
          overwrite-repo-visibility: true # overwrite repo visibility with what is in yml file; defaults to false
          force-push: true
